# Generated by Django 6.0.1 on 2026-01-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la startup')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(upload_to='startups/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gérant')),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
